<a href="https://colab.research.google.com/github/Abhigyan76/Movie-Recommendation-System/blob/main/Day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd

Numpy matrix.max()

In [3]:
gfg = np.matrix('[64, 1; 12, 3]')

In [4]:
geeks = gfg.max()

In [5]:
geeks

64

Q2

In [6]:
gfg = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]')

In [7]:
geeks = gfg.max()
geeks

9

Numpy matrix.take()

In [17]:
gfg = np.matrix('[4, 1, 12, 3, 4, 6, 7]')

In [18]:
geek = gfg.take(2)
geek

matrix([[12]])

Q2

In [19]:
gfg= np.matrix('[4,1,9;12,3,1;4,5,6]')

In [21]:
geek=gfg.take(0,1)

In [22]:
geek

matrix([[ 4, 12,  4]])

Numpy matrix.sum()

In [23]:
gfg = np.matrix('[4, 1; 12, 3]')
             

In [24]:
geek=gfg.sum()

In [25]:
geek

20

Calculate the sum of the diagonal elements of a NumPy array

In [26]:
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

In [27]:
print("Numpy Matrix is:")
print(n_array)
  

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]


In [28]:
trace = np.trace(n_array)

In [30]:
print("\nTrace of given 3X3 matrix:")
print(trace)


Trace of given 3X3 matrix:
176


For 4X4 Numpy matrix

In [31]:
n_array = np.array([[55, 25, 15, 41],
                    [30, 44, 2, 54],
                    [11, 45, 77, 11],
                    [11, 212, 4, 20]])
  

In [32]:
print("Numpy Matrix is:")
print(n_array)

Numpy Matrix is:
[[ 55  25  15  41]
 [ 30  44   2  54]
 [ 11  45  77  11]
 [ 11 212   4  20]]


In [33]:
trace = np.trace(n_array)

In [34]:
print("\nTrace of given 4X4 matrix:")
print(trace)


Trace of given 4X4 matrix:
196


Pandas DataFrame with two-dimensional list

In [35]:
lst = [['tom', 'reacher', 25], ['krish', 'pete', 30], 
       ['nick', 'wilson', 26], ['juli', 'williams', 22]]

In [36]:
df = pd.DataFrame(lst, columns =['FName', 'LName', 'Age'],
                                           dtype = float) 

<ipython-input-36-83a0360863d4>:1: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df = pd.DataFrame(lst, columns =['FName', 'LName', 'Age'],


In [37]:
df

FName     LName   Age
0    tom   reacher  25.0
1  krish      pete  30.0
2   nick    wilson  26.0
3   juli  williams  22.0

rename columns in Pandas DataFrame

In [38]:
rankings = {'test': ['India', 'South Africa', 'England',
                            'New Zealand', 'Australia'],
            'odi': ['England', 'India', 'New Zealand',
                            'South Africa', 'Pakistan'],
            't20': ['Pakistan', 'India', 'Australia',
                            'England', 'New Zealand']}

In [39]:
rankings_pd = pd.DataFrame(rankings)

In [41]:
rankings_pd

test           odi          t20
0         India       England     Pakistan
1  South Africa         India        India
2       England   New Zealand    Australia
3   New Zealand  South Africa      England
4     Australia      Pakistan  New Zealand

In [42]:
rankings_pd.rename(columns = {'test':'TEST'}, inplace = True)

In [43]:
print("\nAfter modifying first column:\n", rankings_pd.columns)


After modifying first column:
 Index(['TEST', 'odi', 't20'], dtype='object')


Rename multiple columns. 

In [44]:
rankings = {'test': ['India', 'South Africa', 'England',
                            'New Zealand', 'Australia'],
              'odi': ['England', 'India', 'New Zealand',
                            'South Africa', 'Pakistan'],
               't20': ['Pakistan', 'India', 'Australia',
                              'England', 'New Zealand']}

In [45]:
rankings_pd = pd.DataFrame(rankings)

In [46]:
rankings_pd.columns

Index(['test', 'odi', 't20'], dtype='object')

In [51]:
a=rankings_pd.rename(columns={'test':'TEST','odi':'ODI','t20':'T20'},inplace=True)

In [52]:
a

By assigning a list of new column names

In [53]:
rankings = {'test': ['India', 'South Africa', 'England',
                            'New Zealand', 'Australia'],
              'odi': ['England', 'India', 'New Zealand',
                            'South Africa', 'Pakistan'],
               't20': ['Pakistan', 'India', 'Australia',
                              'England', 'New Zealand']}

In [54]:
rankings_pd = pd.DataFrame(rankings)

In [55]:
rankings_pd.columns

Index(['test', 'odi', 't20'], dtype='object')

In [57]:
rankings_pd.columns = ['TEST', 'ODI', 'T-20']
rankings_pd.columns

Index(['TEST', 'ODI', 'T-20'], dtype='object')

Rename column names using DataFrame set_axis() function

In [58]:
rankings = {'test': ['India', 'South Africa', 'England',
                     'New Zealand', 'Australia'],
            'odi': ['England', 'India', 'New Zealand',
                    'South Africa', 'Pakistan'],
            't20': ['Pakistan', 'India', 'Australia',
                    'England', 'New Zealand']}

In [59]:
rankings_pd = pd.DataFrame(rankings)

In [60]:
rankings_pd.columns

Index(['test', 'odi', 't20'], dtype='object')

In [61]:
rankings_pd.set_axis(['A', 'B', 'C'], axis='columns', inplace=True)

<ipython-input-61-c194c8f3a198>:1: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  rankings_pd.set_axis(['A', 'B', 'C'], axis='columns', inplace=True)


In [62]:
rankings_pd.columns

Index(['A', 'B', 'C'], dtype='object')

In [63]:
rankings_pd.head()

A             B            C
0         India       England     Pakistan
1  South Africa         India        India
2       England   New Zealand    Australia
3   New Zealand  South Africa      England
4     Australia      Pakistan  New Zealand